version: '3'

services:
  skedway_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skedway_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - skedway_db
      - skedway_redis
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  skedway_db:
    image: mysql:8.0
    container_name: skedway_db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  skedway_redis:
    image: redis:alpine
    container_name: skedway_redis
    ports:
      - "6379:6379"
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
